### ISSUE TITLE
Strange AI behavior

### ISSUE THREAD

**Issue by DmitryRumiantsev** [toyknight/project_aeii#17]
In some cases, when an enemy unit would normally attack, but won't inflict any damage or negative status effect (for example, a soldier attacking a golem on the mountain terrain), it just waits a few seconds and skips it's action instead(even if it can attack other character, or retreat to get healed, or do some other useful thing). Sometimes this also happens with the first enemy unit who gains a turn after you end your turn. Can this be fixed, or is it intended behavior (enemy unit gets so demoralised that he decides to give up on acting and living)?

**Comment by toyknight** [comment]
Well when a unit is low on HP which means it can deal very little damage, it will usually do nothing. And for the case that soldiers attacking golems on the mountain, the estimated damage should be 0 so the AI will also choose not to attack. Maybe I will improve this logic on ranged units since even if the damage is 0 they will not be counter attacked and can still gain attack experience.

As for the retreating and getting healed, it needs a lot of planning (e.g. is this unit worth saving? which method should be chosen to heal it?) so it will make the algorithm really complicated. And there's also a strategy vs AI in the original version that you can choose not to kill enemy units but to damage them to low HP so they lose battle ability. Since AI will retreat low units and have poor healing plans, if you keep doing this you will find that most AI units are low on HP and AI cannot buy any more units due to the unit capacity. Then you can do some save up and defeat AI really easily (this also works for 1 vs 3 AI). So for now I simply do not retreat units with low HP.

**Comment by DmitryRumiantsev** [comment]
Thanks for the explanation, I didn't consider unit capacity while analysing AI behaviour. As for the algorithm for getting units healed, it's definitely seems very situational, especially when the army is tighly packed, but the AI needs to purchase an important situational unit (which means sacrificing someone). It may be good to introduce parameters like unit priority, based on unit's cost, amount of health,experience level and the general situation on the field. For example, check if you're army is stronger than opponents and how far are you in his territory, which type of damage the unit does and what are it's defences. Then check enemy unit attack types, if you're battling on your territory, and defence types otherwise. Then make a guess about the unit's usefulness (like, generally, golem's value would be high if you're defending and the enemy has a lot of physical attackers, or  dragon's value would be high if you're attacking and the enemy has a lot of physical defenders). But when you add special abilities to this it gets really complicated, and I have no idea how to do this reasonably (other than imagi_ng yourself to be a player and carefully considering all the general cases of both armies having or not having units and combination of units, and the distances between them).

I also noticed that when you have enough of different experienced units AI loses advantage over the course of battle it just tends to purchase a lot of soldiers and cannot effectively defend itself. Yet while AI has the upper hand he is often (but not always) able to effectively purchase situational units like spirits. I vaguely remember that in the original game the AI could be very punishing if you switch from defense to attack too early, but there you could be more daring and expect less resistance. It's not necessarily a bad thing, but it makes almost any battle with AI more amusing than challenging when you get the upper hand.

Oh, and one more question, although this is hardly related to the problem. Why have you decided to abandon classical leveling system? In this game, the difference between level 0 and level 1 seems to be drastic, yet it requires relatively little effort to advance any unit this much.

**Comment by toyknight** [comment]
Thanks for your suggestions. As for the leveling system, I changed level cap to 3 mainly for quickening the game pace and make the game more fun to play (especially in PVP mode). Since you know, when a unit levels up it gets somewhat big bonus, it becomes essential to watch for enemy units experience status and kill high threat units before they level up (this gives players another choice to quickly gain advantage instead of occupying enemy villages). So in PVP mode, when a player makes a mistake like failed to kill an enemy key unit and let it successfully retreated or saved by healers, he will be punished hardly later when this enemy unit levels up. This results in a more challenging PVP game where you should try leveling up important units while preventing opponents to level up their units.

**Comment by DmitryRumiantsev** [comment]
That makes perfect sense. In fact, I found myself playing exactly this way instead of focusing on villages and economic advantage.

Concerning the issue when the first AI unit is not attacking, it almost always happens when the attacked unit can apply a negative effect ( like poisoning) on the attacker. I understand that AI is probably not doing this, because the units can't retreat to get healed, but this way it often misses an opportunity to level up its units quickly(like killing a skeleton).
And could you please explain why AI likes to purchase a lot of soldiers when it starts to lose?

**Comment by toyknight** [comment]
For whether or not AI should attack an enemy unit I am planning to improve the logic on that in the future. As to the case you described that AI is not attacking a unit which can apply negative effect, I personally think the reason is that the unit cannot find a target to deal enough damage (like 10+). So if you encounter that situation next time, just pay attention and see if what I said is true.

As for why AI purchase a lot of soldiers is probably because of: 
1. AI is low on gold
2. Your team's average physical defence is lower then/equal to average magic defence so AI wants to purchase physical attacking units (AI mainly uses archers against air forces so it will pass them).
3. AI will not do save ups when it can purchase any unit with preferred attack type.
So in this case when AI have less then 300 gold it will only purchase soldiers. For the case when AI have less then 450 gold, if the first unit AI purchases is soldier (which has a 50% chance) then the following units AI purchases will also be soldiers.

However when your team's average physical defence is greater then average magic defence, AI will do some save up and purchase magic attacking units.

Anyway I have to admit that the current AI purchasing logic is somewhat stupid and I am planning to improve that too.

Hope it helps.

**Comment by toyknight** [comment]
ea51360a466dcd941c0fa856dc3a0e71b5907e45 closes #17
